# Generated by Django 4.0.4 on 2022-06-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_courseteachers_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ("course", "num")},
        ),
    ]
