# Generated by Django 4.0.4 on 2022-06-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_lesson_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ("course", "num"), "verbose_name": "Lesson", "verbose_name_plural": "Lessons"},
        ),
    ]
